CREATE TABLE USERS (
    USER_ID INT PRIMARY KEY AUTO_INCREMENT,
    F_NAME VARCHAR(30),
    L_NAME VARCHAR(30),
    EMAIL VARCHAR(255),
    PASSWORD VARCHAR(255),
    ORGANIZATION BOOLEAN,
    ADMIN BOOLEAN,
    NOTIFICATIONS BOOLEAN
);

CREATE TABLE CATEGORIES(
    CATEGORY_ID INT PRIMARY KEY AUTO_INCREMENT,
    CATEGORY_NAME VARCHAR(30)
);

CREATE TABLE STATUS (
    STATUS_ID INT PRIMARY KEY AUTO_INCREMENT,
    STATUS_DESCR VARCHAR(255)
);

CREATE TABLE EVENTS (
    EVENT_ID INT PRIMARY KEY AUTO_INCREMENT,
    EVENT_NAME VARCHAR(30),
    EVENT_DESCR VARCHAR(255),
    STREET_ADD VARCHAR(255),
    CITY VARCHAR(30),
    ZIPCODE INT,
    CREATOR INT,
    CATEGORY INT,
    DATETIME DATETIME,
    WEBSITE VARCHAR(255),
    LATITUDE FLOAT(10,6),
    LONGITUDE FLOAT (10,6),
    FOREIGN KEY (CREATOR) REFERENCES USERS(USER_ID),
    FOREIGN KEY (CATEGORY) REFERENCES CATEGORIES(CATEGORY_ID)
);

CREATE TABLE EVENT_STATUS (
    USER_ID INT,
    EVENT_ID INT,
    STATUS_ID INT,
    PRIMARY KEY (USER_ID, EVENT_ID),  
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),  
    FOREIGN KEY (EVENT_ID) REFERENCES EVENTS(EVENT_ID),  
    FOREIGN KEY (STATUS_ID) REFERENCES STATUS(STATUS_ID)  
);

CREATE TABLE `REVIEWS` (
  `REVIEWID` int(11) NOT NULL,
  `USERID` int(11) NOT NULL,
  `EVENTID` int(11) NOT NULL,
  `COMMENT` VARCHAR(255) NOT NULL,
  `STARS` int(11) NOT NULL
)

